blank_issues_enabled: false

contact_links:
  - name: LNCrawler Documentation
    url: https://github.com/Binit06/LNCrawler#readme
    about: Read the documentation before opening an issue.

  - name: LNCrawlerSources
    url: https://github.com/Binit06/LNCrawlerSources
    about: Report crawler-specific issues and contribute new crawlers here.